language: node_js
node_js:
  - "4.1"
install:
  - "npm install --only=dev"
before_script:
  - "npm run dts"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
    - $HOME/.dtsm
